/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#bdb2ff",
        "secondary": "#5f559a",
        "error-container": "#ffdad6",
        "background": "#f9f9ff",
        "surface": "#f9f9ff",
        "on-primary-fixed": "#001a41",
        "on-surface-variant": "#414754",
        "primary-fixed": "#d8e2ff",
        "on-tertiary": "#ffffff",
        "surface-variant": "#d8e3fb",
        "outline-variant": "#c2c6d6",
        "on-secondary-fixed": "#1b0c53",
        "surface-bright": "#f9f9ff",
        "on-tertiary-fixed-variant": "#5b3f47",
        "secondary-fixed": "#e5deff",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#473d81",
        "inverse-on-surface": "#ecf1ff",
        "on-surface": "#111c2d",
        "surface-container-high": "#dee8ff",
        "tertiary-fixed": "#ffd9e2",
        "on-tertiary-fixed": "#2b151c",
        "on-tertiary-container": "#fffbff",
        "tertiary": "#72545c",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#c8bfff",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "outline": "#727785",
        "primary-fixed-dim": "#adc6ff",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#004494",
        "on-primary-container": "#fefcff",
        "tertiary-container": "#8d6c75",
        "on-error-container": "#93000a",
        "surface-dim": "#cfdaf2",
        "on-secondary-container": "#4b4185",
        "inverse-surface": "#263143",
        "primary": "#0058bd",
        "surface-container-highest": "#d8e3fb",
        "surface-container": "#e7eeff",
        "surface-tint": "#005ac2",
        "inverse-primary": "#adc6ff",
        "surface-container-low": "#f0f3ff",
        "primary-container": "#1470e8",
        "tertiary-fixed-dim": "#e4bcc6",
        "on-background": "#111c2d"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        margin: "1rem",
        "space-xs": "0.25rem",
        "space-md": "0.75rem",
        "space-sm": "0.5rem",
        "space-lg": "1.25rem",
        "gutter-desktop": "1.5rem",
        gutter: "1rem",
        "margin-desktop": "2rem",
        "space-xl": "2rem"
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "numeric-data": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "numeric-data": ["13px", { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
